# Generated by Django 3.1.7 on 2021-03-20 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210320_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='created',
        ),
    ]
