# Generated by Django 3.1.7 on 2021-03-20 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210320_0939'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tasks',
            table=None,
        ),
    ]
